c++: reverse.cc
	clang++ -o reverse reverse.cc -Wall -Werror -mlinker-version=450
	./reverse Makefile output.txt output.txt # Err
	./reverse test.txt test.txt # Err
	echo "Hello" | ./reverse
	./reverse Makefile
	./reverse Makefile output.txt
